server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # ==========================
        # API JSON
        # ==========================

        - id: articulos-service
          uri: http://articulos-service:8081
          predicates:
            - Path=/api/articulos/**

        - id: categorias-service
          uri: http://categorias-service:8082
          predicates:
            - Path=/api/categorias/**

        - id: comentarios-service
          uri: http://comentarios-service:8083
          predicates:
            - Path=/api/comentarios/**

        - id: usuarios-service
          uri: http://usuarios-service:8084
          predicates:
            - Path=/api/usuarios/**

        - id: notificaciones-service
          uri: http://notificaciones-service:8085
          predicates:
            - Path=/api/notificaciones/**

        - id: reacciones-service
          uri: http://reacciones-service:8086
          predicates:
            - Path=/api/reacciones/**

        - id: favoritos-service
          uri: http://favoritos-service:8087
          predicates:
            - Path=/api/favoritos/**

        # ==========================
        # VISTAS HTML - THYMELEAF
        # ==========================

        - id: articulos-vista
          uri: http://articulos-service:8081
          predicates:
            - Path=/articulos/**

        - id: categorias-vista
          uri: http://categorias-service:8082
          predicates:
            - Path=/categorias/**

        - id: comentarios-vista
          uri: http://comentarios-service:8083
          predicates:
            - Path=/comentarios/**

        - id: usuarios-vista
          uri: http://usuarios-service:8084
          predicates:
            - Path=/usuarios/**

        - id: notificaciones-vista
          uri: http://notificaciones-service:8085
          predicates:
            - Path=/notificaciones/**

        - id: reacciones-vista
          uri: http://reacciones-service:8086
          predicates:
            - Path=/reacciones/**

        - id: favoritos-vista
          uri: http://favoritos-service:8087
          predicates:
            - Path=/lista/**

management:
  endpoints:
    web:
      exposure:
        include: "*"